# app/config/config.yml
parameters:
  mailer_user: "sunthings05@gmail.com"

fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "%mailer_user%"
    sender_name: "%mailer_user%"