version: '2'

services:
    mysql:
        build: docker/mysql
        ports:
            - 3308:3306
        restart: always
        #privileged: true
        volumes:
            - ./docker/data/mysql:/var/lib/mysql:delegated,rw
        environment:
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE: student
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
        networks:
            - app
        user: root
    php:
        container_name: php
        build: docker/php/
        ports:
            - 9001:9000
        restart: always
        volumes:
            - ./:/var/www/symfony:cached
            - /etc/timezone:/etc/timezone:cached
        networks:
            - app
    nginx:
        build: docker/nginx/
        ports:
            - 80:80
        restart: always
        volumes_from:
            - php
        networks:
            - app
networks:
    app:
        driver: bridge

volumes:
    data:
        driver: local